# Generated by Django 4.2.4 on 2024-02-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
